import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Voting  App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap" rel="stylesheet"/>

      </Head>

      <main className=" my-20 font-raleway">
            <div className='bg-black w-[70%] mx-auto'>

          <h2 className=' p-8 text-4xl font-bold text-center animate-gradient bg-clip-text text-transparent bg-gradient-to-r from-white to-purple-700'>Chain Master Decentralized Voting System</h2>
            </div>
            <div className='h-40 bg-black mt-10 gap-4 w-[70%] items-center flex mx-auto'>
  <div className='h-[80%] text-white  text-[1.3rem] bg-[#4f015b] text-[]  flex-1 flex justify-center items-center'> spanNo  of Voters : 0</div>
  <div className='h-[80%] text-white text-[1.3rem] bg-[#4f015b] flex-1 flex justify-center items-center'> No of Vote : 0</div>
  <div className='h-[80%] text-white text-[1.3rem] bg-[#4f015b] flex-1 flex justify-center items-center'> No of Proposal :0</div>
</div>
      </main>

     
    </div>
  );
};

export default Home;
